name = input("What's your name?: ")
food = input("What's your favorite food?: ")
music = input("What is your favorite music?: ")
live = input("Where do you live?: ")

print()
print()
print("Hello there")
print(name)
print("I hear you like..")
print(food)
print("I also like")
print(music)
print("Thats funny many years ago I use to live in")
print(live)
