print("#### YOUR ADVENTURE SIMULATOR ####")
print("I'll be asking you some questions, and we will take your answers and turn it into a story where you are the main character")
print()
print('##################################')
name = input("What will be your Hero's name?: ")
super_power = input("What do you want your super power to be?: ")
kingdom = input("What will be the name of the kingdom you are from?: ")
villan = input("What will be the name of the villan in this story?: ")
midevil_job = input("What is a midevil occupation?: ")
print()

print("This story begins in a distant kingdom named",kingdom)
print("With a lowly pesant named", name, "who was working as a", midevil_job)
print("One day", name, "was working when", villan, "decided to pick a fight with him, and beat", name, "up!")
print(name, "swore one day he would get his justice, and just then he was stung by a misterious instect and suddenly had the power to", super_power)
print("The next day,", villan, "came by to pick another fight, but was super surprised how quickly he was defeated now that", name, "had the power of", super_power,"!")
print()
print(villan, "learned his lesson, and from that day on,", name, "used his powers to fight evil and peace was restored to", kingdom)
print("THE END!")
